version: "3.8"

networks:
  Proxy:
    external:
      name: Proxy

services: 
  influxdb:
    restart: unless-stopped
    image: influxdb:latest
    networks: 
      - Proxy
    labels: 
      - "traefik.enable=true"
      - "traefik.http.middlewares.influxdb-http-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.influxdb-http.middlewares=influxdb-http-to-https@docker"
      - "traefik.http.routers.influxdb-http.rule=Host(`influxdb.local.nksl.eu`)"
      - "traefik.http.routers.influxdb-https.rule=Host(`influxdb.local.nksl.eu`)"
      - "traefik.http.routers.influxdb-https.tls=true"
      - "traefik.http.services.influxdb-https.loadbalancer.server.port=8086"
    volumes: 
      - ./files/influxdb/data:/var/lib/influxdb2
      - ./files/influxdb/config:/etc/influxdb2

  data_collector:
    restart: unless-stopped
    build: ./images/data_collector
    depends_on: 
      - influxdb
    
