version: "3.8"

networks:
  Proxy:
    external:
      name: Proxy

services: 
  influxdb:
    restart: unless-stopped
    image: influxdb:latest
    networks: 
      - Proxy
    ports:
      - 8086:8086
    labels: 
      - "traefik.enable=true"
      - "traefik.http.middlewares.influxdb-http-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.influxdb-http.middlewares=influxdb-http-to-https@docker"
      - "traefik.http.routers.influxdb-http.rule=Host(`influxdb.local.nksl.eu`)"
      - "traefik.http.routers.influxdb-https.rule=Host(`influxdb.local.nksl.eu`)"
      - "traefik.http.routers.influxdb-https.tls=true"
      - "traefik.http.services.influxdb-https.loadbalancer.server.port=8086"
    volumes: 
      - ./files/influxdb/data:/var/lib/influxdb2
      - ./files/influxdb/config:/etc/influxdb2
    environment: 
      INFLUXD_LOG_LEVEL: debug

  # data_collector:
  #   restart: unless-stopped
  #   build: ./images/data_collector
  #   volumes:
  #     - ./files/data_collector/config.ini:/usr/src/app/config.ini
  #     - ./files/data_collector/nut_servers.ini:/usr/src/app/nut_servers.ini
  #   depends_on: 
  #     - influxdb
    
